### ISSUE TITLE
test_iface_wino_convolution failed on AArch64

### ISSUE THREAD

**Issue by kawakami-k** [oneapi-src/oneDNN#1577]
# Summary
`tests/gtests/test_iface_wino_convolution` failed on AArch64 environment.

# Version

```
local:SVE512 /home/kawakami2/mkldnn/oneDNN_intel/build/tests/gtests% git log -1 --format=%H
9ce03ba511e94659adc8e0122b1c6e6fd65637a1
```

# Environment

```
local:SVE512 /home/kawakami2/mkldnn/oneDNN_intel/build/tests/gtests% lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              48
On-line CPU(s) list: 0-47
Thread(s) per core:  1
Core(s) per socket:  12
Socket(s):           4
NUMA node(s):        4
Vendor ID:           0x46
Model:               0
Stepping:            0x1
BogoMIPS:            200.00
NUMA node0 CPU(s):   0-11
NUMA node1 CPU(s):   12-23
NUMA node2 CPU(s):   24-35
NUMA node3 CPU(s):   36-47
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm fcma dcpop sve
local:SVE512 /home/kawakami2/mkldnn/oneDNN_intel/build/tests/gtests% git log -1 --format=%H
9ce03ba511e94659adc8e0122b1c6e6fd65637a1
local:SVE512 /home/kawakami2/mkldnn/oneDNN_intel/build/tests/gtests% lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              48
On-line CPU(s) list: 0-47
Thread(s) per core:  1
Core(s) per socket:  12
Socket(s):           4
NUMA node(s):        4
Vendor ID:           0x46
Model:               0
Stepping:            0x1
BogoMIPS:            200.00
NUMA node0 CPU(s):   0-11
NUMA node1 CPU(s):   12-23
NUMA node2 CPU(s):   24-35
NUMA node3 CPU(s):   36-47
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm fcma dcpop sve
local:SVE512 /home/kawakami2/mkldnn/oneDNN_intel/build/tests/gtests% uname -a
Linux local 4.18.0-240.el8.aarch64 #1 SMP Fri Sep 25 19:32:19 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
local:SVE512 /home/kawakami2/mkldnn/oneDNN_intel/build/tests/gtests% gcc --version
gcc (GCC) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

local:SVE512 /home/kawakami2/mkldnn/oneDNN_intel/build/tests/gtests% cmake --version
cmake version 3.11.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
local:SVE512 /home/kawakami2/mkldnn/oneDNN_intel/build/tests/gtests% git log -1 --format=%H
9ce03ba511e94659adc8e0122b1c6e6fd65637a1
```

# Steps to reproduce
```
 .github/automation/build.sh --threading omp --mode Release --source-dir $(pwd) --build-dir $(pwd)/build_generic
cd build/tests/gtests
./test_iface_wino_convolution
```

# Observed behavior

```
local:SVE512 /home/kawakami2/mkldnn/oneDNN_intel/build/tests/gtests% ./test_iface_wino_convolution 
Note: Google Test filter = *:-*_GPU*
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from wino_conv_test_t
[ RUN      ] wino_conv_test_t.TestSmallPadding
/home/kawakami2/mkldnn/oneDNN_intel/tests/gtests/test_iface_wino_convolution.cpp:100: Failure
Expected: convolution_forward::primitive_desc(eng, prop_kind::forward, algorithm::convolution_winograd, src_md, wei_md, dst_md, {1, 1}, {1, 1}, {1, 1}) throws an exception.
  Actual: it doesn't.
/home/kawakami2/mkldnn/oneDNN_intel/tests/gtests/test_iface_wino_convolution.cpp:100: Failure
Expected: convolution_forward::primitive_desc(eng, prop_kind::forward, algorithm::convolution_winograd, src_md, wei_md, dst_md, {1, 1}, {1, 1}, {1, 1}) throws an exception.
  Actual: it doesn't.
[  FAILED  ] wino_conv_test_t.TestSmallPadding (1 ms)
[ RUN      ] wino_conv_test_t.TestLargePadding
[       OK ] wino_conv_test_t.TestLargePadding (0 ms)
[ RUN      ] wino_conv_test_t.TestUnsupportedKernel
[       OK ] wino_conv_test_t.TestUnsupportedKernel (0 ms)
[----------] 3 tests from wino_conv_test_t (1 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (1 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] wino_conv_test_t.TestSmallPadding

 1 FAILED TEST
```

# Expected behavior

There is no JIT-ed implementation of winograd convolution for AArch64 at this time. 
`test_iface_wino_convolution` seems to expect an exception to be send.
https://github.com/oneapi-src/oneDNN/blob/9ce03ba511e94659adc8e0122b1c6e6fd65637a1/tests/gtests/test_iface_wino_convolution.cpp#L100-L102

How should I handle this case? This error may also occurs on other architectures except x64.

**Comment by kawakami-k** [comment]
https://github.com/oneapi-src/oneDNN/blob/9ce03ba511e94659adc8e0122b1c6e6fd65637a1/tests/gtests/test_iface_wino_convolution.cpp#L124
https://github.com/oneapi-src/oneDNN/blob/9ce03ba511e94659adc8e0122b1c6e6fd65637a1/tests/gtests/test_iface_wino_convolution.cpp#L143
Since `DNNL_X64` is defined as zero, should `!defined(DNNL_X64)` in the above lines be modified to `DNNL_X64==0`?
https://github.com/oneapi-src/oneDNN/blob/9ce03ba511e94659adc8e0122b1c6e6fd65637a1/src/cpu/platform.hpp#L63

**Comment by vpirogov** [comment]
This should be addressed by 33e68afc99dfc7b21c64022d15eb97fa1a117807.

**Comment by ggardet** [comment]
> This should be addressed by [33e68af](https://github.com/oneapi-src/oneDNN/commit/33e68afc99dfc7b21c64022d15eb97fa1a117807).

v3.4.1 with https://github.com/oneapi-src/oneDNN/commit/33e68afc99dfc7b21c64022d15eb97fa1a117807 still fails on aarch64, but the error message looks a bit different:
```
[ 1481s] 61/99 Test #64: test_iface_wino_convolution .............................***Failed    0.10 sec
[ 1481s] Note: Google Test filter = *:-*_GPU*
[ 1481s] [==========] Running 3 tests from 1 test suite.
[ 1481s] [----------] Global test environment set-up.
[ 1481s] [----------] 3 tests from wino_conv_test_t
[ 1481s] [ RUN      ] wino_conv_test_t.TestSmallPadding
[ 1481s] /home/abuild/rpmbuild/BUILD/oneDNN-3.4.1/tests/gtests/test_iface_wino_convolution.cpp:78: Failure
[ 1481s] Expected: fwd_hint = convolution_forward::primitive_desc(eng, prop_kind::forward, algorithm::convolution_winograd, src_md, wei_md, dst_md, {1, 1}, {1, 1}, {1, 1}) doesn't throw an exception.
[ 1481s]   Actual: it throws dnnl::error with description "could not create a primitive descriptor for a convolution forward propagation primitive".
[ 1481s] [  FAILED  ] wino_conv_test_t.TestSmallPadding (0 ms)
[ 1481s] [ RUN      ] wino_conv_test_t.TestLargePadding
[ 1481s] [       OK ] wino_conv_test_t.TestLargePadding (0 ms)
[ 1481s] [ RUN      ] wino_conv_test_t.TestUnsupportedKernel
[ 1481s] [       OK ] wino_conv_test_t.TestUnsupportedKernel (0 ms)
[ 1481s] [----------] 3 tests from wino_conv_test_t (0 ms total)
[ 1481s] 
[ 1481s] [----------] Global test environment tear-down
[ 1481s] [==========] 3 tests from 1 test suite ran. (12 ms total)
[ 1481s] [  PASSED  ] 2 tests.
[ 1481s] [  FAILED  ] 1 test, listed below:
[ 1481s] [  FAILED  ] wino_conv_test_t.TestSmallPadding
[ 1481s] 
[ 1481s]  1 FAILED TEST
```
