### ISSUE TITLE
test_benchdnn_matmul_ci_cpu fails on aarch64 with and without the Compute Library backend 

### ISSUE THREAD

**Issue by fadara01** [oneapi-src/oneDNN#1785]
# Summary
`test_benchdnn_matmul_ci_cpu` fails on aarch64 with and without the Compute Library (ACL) backend 

# Version
oneDNN version: main and githash = `7a2cfca664f3f59096349625a7c424ab4be4ada3` .

# Environment
* CPU: Neoverse-V1 / Neoverse-N1 (aarch64)
* OS version: `20.04.1-Ubuntu`
* Compiler version: `gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2)`
* CMake version: `3.16.3`
* git hash: `7a2cfca664f3f59096349625a7c424ab4be4ada3`

# Steps to reproduce
Compile (with or without the Compute Library backend) and run `ctest -R test_benchdnn_matmul_ci_cpu`

# Observed behavior
`test_benchdnn_matmul_ci_cpu` has 12 failures, all of which occur when `--attr-post-ops=prelu`
Here is the log for running `ctest -V -R test_benchdnn_matmul_ci_cpu` : 
[test_benchdnn_matmul_ci_cpu.log](https://github.com/oneapi-src/oneDNN/files/13916501/test_benchdnn_matmul_ci_cpu.log).
Note that the implementation name reported in the verbose of the failing tests is: `gemm:jit:f32`
# Expected behavior
All tests pass

**Comment by vpirogov** [comment]
@fadara01, could you please include information on specific failing test case and error message benchdnn produces on fail?

**Comment by fadara01** [comment]
Hi @vpirogov - I added output logs and more details to the issue description.

**Comment by vpirogov** [comment]
Thanks, @fadara01. Looks like the fails are specific to `prelu:per_tensor` post-op cases:
```
run: --matmul --dt=u8:s8:s8 --attr-post-ops=prelu:per_tensor 3x30x1:3x1x20
[   1][DST][0:0:1] exp_f32:       -1.25 exp:          -1 got:         -20 diff:      19 rdiff:      19
[   2][DST][0:0:2] exp_f32:         -40 exp:         -40 got:          -5 diff:      35 rdiff:   0.875
[   4][DST][0:0:4] exp_f32:          -5 exp:          -5 got:          10 diff:      15 rdiff:       3
[   5][DST][0:0:5] exp_f32:          10 exp:          10 got:         -80 diff:      90 rdiff:       9
[   6][DST][0:0:6] exp_f32:         -40 exp:         -40 got:          -5 diff:      35 rdiff:   0.875
[   7][DST][0:0:7] exp_f32:         -40 exp:         -40 got:          -5 diff:      35 rdiff:   0.875
[   9][DST][0:0:9] exp_f32:        -120 exp:        -120 got:         -60 diff:      60 rdiff:     0.5
[  11][DST][0:0:11] exp_f32:       -1.25 exp:          -1 got:         -20 diff:      19 rdiff:      19
[  12][DST][0:0:12] exp_f32:         -20 exp:         -20 got:          10 diff:      30 rdiff:     1.5
[  13][DST][0:0:13] exp_f32:         -15 exp:         -15 got:         -60 diff:      45 rdiff:       3
[COMPARE_STATS][DST]: trh=0 max_diff:     255 max_rdiff:      71
[PRIM_REF][INFO]: L2_size:524288 bytes; per_core_L3_size:1048576 bytes; nthr:64; impl_name:gemm:jit:f32
[PRIM_REF][REPRO]: --matmcl --attr-post-ops=prelu:per_tensor 3x30x1:3x1x20
879:FAILED (errors:842 total:1800) __REPRO: --matmul --dt=u8:s8:s8 --attr-post-ops=prelu:per_tensor 3x30x1:3x1x20
```

**Comment by vpirogov** [comment]
This is an issue in reference implementation that should be fixed by b26625c1c5bfa51951e1551162ebce165a6e8427. Please confirm.

**Comment by aaraujom** [comment]
@fadara01 - Could you try commit https://github.com/oneapi-src/oneDNN/commit/b26625c1c5bfa51951e1551162ebce165a6e8427 to check if addresses your issue?

**Comment by jondea** [comment]
Hi @aaraujom, sorry for the delay. This is still failing for the same reason on b26625c1c5 and on current main (as of 03135b9a89)

**Comment by aaraujom** [comment]
> Hi @aaraujom, sorry for the delay. This is still failing for the same reason on https://github.com/oneapi-src/oneDNN/commit/b26625c1c5bfa51951e1551162ebce165a6e8427 and on current main (as of https://github.com/oneapi-src/oneDNN/commit/03135b9a89794782c5ab31264daf4a1f44368d85)

Thank you. Let me check what is going on.

**Comment by aaraujom** [comment]
I can reproduce the issue locally. Still debugging it though.

**Comment by aaraujom** [comment]
@jondea - The issue is actually a problem with testing in benchdnn. Fix for benchdnn is underway (thanks @dzarukin). I've just wanted to point out that library computations are indeed correct.

**Comment by aaraujom** [comment]
@jondea - Could you try main branch one more time. It test should be fixed with this commit https://github.com/oneapi-src/oneDNN/commit/9944d2b73c4a1556859547689211894f1afb7518.

**Comment by fadara01** [comment]
Thanks for resolving this!
